import 'dart:io';
import 'dart:convert';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:file_picker/file_picker.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:traktstats/provider/operationMode.dart';
import 'package:traktstats/screens/mainscreen.dart';


class Homescreen extends StatelessWidget {
  const Homescreen({super.key});

  Future<void> takeToGithubRepoOfTraktstats() async {
      final Uri url = Uri.parse('https://github.com/Ahmedazim7804/trakt_vip_stats');
      if (!await launchUrl(url)) {
        throw Exception('Could not launch $url');
      }
    }

  Widget infoDialog(BuildContext ctx) {

    RichText content = RichText(text: TextSpan(
      children: [
        const TextSpan(text: 'Select the json generated by '),
        TextSpan(
          text: 'traktstats',
          style: const TextStyle(color: Colors.blue),
          recognizer: TapGestureRecognizer()..onTap = () => takeToGithubRepoOfTraktstats())
        ]
    ));

    return AlertDialog(
      content: content,
      actions: [TextButton(onPressed: () {Navigator.of(ctx).pop();}, child: const Text("Ok"))],
      backgroundColor: Colors.black,
      shape: const BeveledRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(5))),
      );
  }

  Future<Map> readJsonFromFile(File? file) async {
    var input = await file!.readAsString();
    Map map = jsonDecode(input);
    return map;
  }


  @override
  Widget build(BuildContext context) {
    TextEditingController textController = TextEditingController();

    void goToMainScreen() {
      Navigator.push(context, MaterialPageRoute(builder: (BuildContext ctx) {return const MainScreen();}));
    }

    void submit() {
      final String url = textController.text;
      Model.baseurl = url;

      if (Uri.parse(url).isAbsolute) {
        goToMainScreen();
      }
    }

    void selectFile() async {
      FilePickerResult? result = await FilePicker.platform.pickFiles();
      if (result != null) {
        File file = File(result.files.single.path!);
        Model.fileData = await readJsonFromFile(file);
      
        if (Model.fileData.isNotEmpty) {
          Model.operationMode = OperationModes.file;
          
          goToMainScreen();
        }
      }
    }

    return Container(
          alignment: Alignment.center,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Image.asset('assets/images/trakt.png'),
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16.0),
                child: TextField(controller: textController, style: const TextStyle(color: Colors.white), cursorColor: Colors.white, decoration: const InputDecoration(hintText: "http://127.0.0.1:8455", hintStyle: TextStyle(color: Colors.white54), label: Text("Server Url", style: TextStyle(color: Colors.white)))),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(vertical: 32),
                child: ElevatedButton(onPressed: submit, style: ElevatedButton.styleFrom(backgroundColor: const Color.fromARGB(200, 235, 28, 36)), child: const Text("Submit", style: TextStyle(color: Colors.white),),),
              ),
              const Text("OR", style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 18),),
              const SizedBox(height: 32,),
              Row(
                mainAxisSize: MainAxisSize.min,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  const SizedBox(width: 50,),
                  ElevatedButton(onPressed: selectFile, style: ElevatedButton.styleFrom(backgroundColor: const Color.fromARGB(200, 235, 28, 36)), child: const Text("Select json file", style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 15),),),
                  IconButton(icon: const Icon(Icons.help), onPressed: () {showDialog(context: context, builder: infoDialog);}),
                ],
              )
            ],
          ),
        );
  }
}